# Generated by Django 3.2.5 on 2021-08-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='Sign',
        ),
    ]
